# Generated by Django 3.0.3 on 2020-03-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_token_userpasswordreset_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpasswordreset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='UserPasswordReset',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
