# Generated by Django 3.0.3 on 2020-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='id',
        ),
        migrations.AddField(
            model_name='tempuser',
            name='auto_increment_id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False),
        ),
    ]
