# Generated by Django 3.0.3 on 2020-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200310_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='auto_increment_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
